"""Create Victims Model, Add one more FK field

Revision ID: 4fffd2e7e07b
Revises: 60eda3e9c483
Create Date: 2024-04-23 01:25:44.931198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fffd2e7e07b'
down_revision = '60eda3e9c483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('victims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dog_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('victims_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'victims', ['victims_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog_cases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('victims_id')

    op.drop_table('victims')
    # ### end Alembic commands ###
