"""Create new Model, Add FK field

Revision ID: 60eda3e9c483
Revises: afd0a38fb379
Create Date: 2024-04-23 01:11:04.829646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60eda3e9c483'
down_revision = 'afd0a38fb379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dog_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evidence_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'evidence', ['evidence_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog_cases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('evidence_id')

    op.drop_table('evidence')
    # ### end Alembic commands ###
