"""Create first model DogCase

Revision ID: afd0a38fb379
Revises: 
Create Date: 2024-04-23 00:04:55.736461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd0a38fb379'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dog_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_type', sa.String(length=45), nullable=False),
    sa.Column('seriousness', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dog_cases')
    # ### end Alembic commands ###
